### ISSUE TITLE
Need to update information

### ISSUE THREAD

**Issue by Rope-a-dope** [AnirudhG07/awesome-yazi#30]
Need to update the command with the updated link. The description in the link [epub.yazi](https://gitee.com/DreamMaoMao/epub.yazi) is also not updated even though the link is gitee instead of github. 
[epub.yazi](https://gitee.com/DreamMaoMao/epub.yazi) - Plugin for Yazi to preview epub file.
```
# Linux
git clone https://gitee.com/DreamMaoMao/epub.yazi ~/.config/yazi/plugins/epub.yazi
```

[eza-preview.yazi](https://github.com/sharklasers996/eza-preview.yazi) - **Preview directories using [eza](https://github.com/eza-community/eza)**

**Comment by AnirudhG07** [comment]
Thanks for pointing this out. I have fixed it in the the mentioned commit.
